/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo_desktop;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kien
 */
public class frmB2 extends javax.swing.JFrame {

    /**
     * Creates new form frmB2
     */
    public frmB2() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        pnXuLy = new javax.swing.JPanel();
        lblSoa = new javax.swing.JLabel();
        lblsoA = new javax.swing.JLabel();
        lblThucHien = new javax.swing.JLabel();
        lblKetQua = new javax.swing.JLabel();
        txtNhapA = new javax.swing.JTextField();
        CboPhepToan = new javax.swing.JComboBox<>();
        txtKetQua = new javax.swing.JTextField();
        txtNhapB = new javax.swing.JTextField();
        btnTinh = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bài tập phần If...Else");

        pnXuLy.setBorder(javax.swing.BorderFactory.createTitledBorder("Xử lý If...Else trong xử lý tính toán"));

        lblSoa.setText("Nhập vào số a:");

        lblsoA.setText("Nhập vào số b:");

        lblThucHien.setText("Chọn phép toán:");

        lblKetQua.setText("Kết quả:");

        CboPhepToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cộng", "Trừ", "Nhân", "Chia" }));
        CboPhepToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboPhepToanActionPerformed(evt);
            }
        });

        btnTinh.setText("Tính toán");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnXuLyLayout = new javax.swing.GroupLayout(pnXuLy);
        pnXuLy.setLayout(pnXuLyLayout);
        pnXuLyLayout.setHorizontalGroup(
            pnXuLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnXuLyLayout.createSequentialGroup()
                .addGroup(pnXuLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnXuLyLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTinh))
                    .addGroup(pnXuLyLayout.createSequentialGroup()
                        .addContainerGap(68, Short.MAX_VALUE)
                        .addGroup(pnXuLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKetQua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblsoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblThucHien, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnXuLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNhapA)
                            .addComponent(CboPhepToan, 0, 208, Short.MAX_VALUE)
                            .addComponent(txtKetQua)
                            .addComponent(txtNhapB))))
                .addGap(80, 80, 80))
        );
        pnXuLyLayout.setVerticalGroup(
            pnXuLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXuLyLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnXuLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoa)
                    .addComponent(txtNhapA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnXuLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsoA)
                    .addComponent(txtNhapB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnXuLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThucHien)
                    .addComponent(CboPhepToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnXuLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnTinh)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnXuLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnXuLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CboPhepToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboPhepToanActionPerformed
        
    }//GEN-LAST:event_CboPhepToanActionPerformed

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        String strA="", strB = "", strPhepTinh="" ,strKetQua = "";
        int a = 0, b = 0, ketQua = 0;
        
        strA = txtNhapA.getText();
        strB = txtNhapB.getText();
        strPhepTinh = ""+CboPhepToan.getSelectedItem();
        if(strA.length()==0){
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập A");
                return;
        }
        if(strB.length()==0){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập B");
            return;
        }
        try {
          
            a = Integer.parseInt(strA);
            b = Integer.parseInt(strB); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Vui lòng nhập lại");
            requestFocus();
        }
        
        switch(strPhepTinh){ 
            case "Cộng":{
                ketQua = a + b;
                strKetQua = ""+ ketQua;
                txtKetQua.setText(strKetQua);
                break;
            }
            case "Trừ":{
                ketQua = a - b;
                strKetQua = ""+ ketQua;
                txtKetQua.setText(strKetQua);
                break;
            }
            case "Nhân":{
               ketQua = a * b;
               strKetQua = ""+ ketQua;
               txtKetQua.setText(strKetQua);
               break; 
            }
            case "Chia":{
                if(b==0)
                    JOptionPane.showMessageDialog(rootPane, "Bạn không thể thực hiện phép chia này");    
                else{
                    ketQua=a/b;
                    strKetQua = ""+ ketQua;
                    txtKetQua.setText(strKetQua);
                } 
                break;
            }
                 
            default: {
                strKetQua ="No ketQua" ;
                txtKetQua.setText(strKetQua);
            }
        }
        
        
    }//GEN-LAST:event_btnTinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmB2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboPhepToan;
    private javax.swing.JButton btnTinh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblKetQua;
    private javax.swing.JLabel lblSoa;
    private javax.swing.JLabel lblThucHien;
    private javax.swing.JLabel lblsoA;
    private javax.swing.JPanel pnXuLy;
    private javax.swing.JTextField txtKetQua;
    private javax.swing.JTextField txtNhapA;
    private javax.swing.JTextField txtNhapB;
    // End of variables declaration//GEN-END:variables
}
