/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo_desktop;

import javax.swing.JOptionPane;

/**
 *
 * @author Kien
 */
public class frmB4 extends javax.swing.JFrame {

    /**
     * Creates new form frmB4
     */
    public frmB4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNhap = new javax.swing.JPanel();
        lblChon = new javax.swing.JLabel();
        cboChon = new javax.swing.JComboBox<>();
        btnXemThongTin = new javax.swing.JButton();
        pnXuat = new javax.swing.JPanel();
        lblKichThuoc = new javax.swing.JLabel();
        lblKieu = new javax.swing.JLabel();
        lblMota = new javax.swing.JLabel();
        txtKichThuoc = new javax.swing.JTextField();
        txtKieu = new javax.swing.JTextField();
        txtMoTa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thông tin các kiểu dữ liệu");

        pnNhap.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn kiểu dữ liệu cần xem thông tin"));

        lblChon.setText("Chọn kiểu dữ liệu:");

        cboChon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "byte", "char", "bool", "long", "short", "ushort", "int", " " }));

        btnXemThongTin.setText("Xem thông tin");
        btnXemThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemThongTinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnNhapLayout = new javax.swing.GroupLayout(pnNhap);
        pnNhap.setLayout(pnNhapLayout);
        pnNhapLayout.setHorizontalGroup(
            pnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChon)
                .addGap(18, 18, 18)
                .addComponent(cboChon, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnXemThongTin)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        pnNhapLayout.setVerticalGroup(
            pnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChon)
                    .addComponent(cboChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemThongTin))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pnXuat.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin kiểu dữ liệu trong java"));

        lblKichThuoc.setText("+ Kích thước(byte):");

        lblKieu.setText("+ Kiểu:");

        lblMota.setText("+ Mô tả - Giá trị:");

        javax.swing.GroupLayout pnXuatLayout = new javax.swing.GroupLayout(pnXuat);
        pnXuat.setLayout(pnXuatLayout);
        pnXuatLayout.setHorizontalGroup(
            pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnXuatLayout.createSequentialGroup()
                        .addComponent(lblKieu)
                        .addGap(18, 18, 18)
                        .addComponent(txtKieu, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(pnXuatLayout.createSequentialGroup()
                        .addComponent(lblMota)
                        .addGap(18, 18, 18)
                        .addComponent(txtMoTa))
                    .addGroup(pnXuatLayout.createSequentialGroup()
                        .addComponent(lblKichThuoc)
                        .addGap(18, 18, 18)
                        .addComponent(txtKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnXuatLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblKichThuoc, lblKieu, lblMota});

        pnXuatLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtKichThuoc, txtKieu, txtMoTa});

        pnXuatLayout.setVerticalGroup(
            pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXuatLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKichThuoc)
                    .addComponent(txtKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKieu)
                    .addComponent(txtKieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMota)
                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemThongTinActionPerformed
        String strChon = "", strKichThuoc = "", strKieu="",strMota="";
        strChon = ""+cboChon.getSelectedItem();
        switch(strChon){
            case "byte":{
                strKichThuoc = "1 Byte";
                strKieu ="Byte";
                strMota = "Không dấu (0-255) ký tự";
                break;
            }
            case "char":{
                strKichThuoc = "2 Byte";
                strKieu ="char";
                strMota = "\\u0000’ to u\\ffff ";
                break;
            }
            case "bool":{
                strKichThuoc = "1 /8 Byte";
                strKieu ="bool";
                strMota = "true or false";
                break;
            }
            case "short":{
                strKichThuoc = "4 Byte";
                strKieu ="short";
                strMota = "-32768 đến 32767";
                break;
            }
            case "int":{
                strKichThuoc = "4 Byte";
                strKieu ="int";
                strMota = "-2,147,483,648 đến +2,147,483,648";
                break;
            }
            case "long":{
                strKichThuoc = "8 Byte";
                strKieu ="long";
                strMota = "-2^63 đến +2^63-1";
                break;
            }
            case "ushort":{
                strKichThuoc = "Range";
                strKieu ="unsigned short int";
                strMota = "0 tới 65,535";
                break;
            }
             default: JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập kiểu dữ liệu");
                
        }
        txtKichThuoc.setText(strKichThuoc);
        txtKieu.setText(strKieu);
        txtMoTa.setText(strMota);
    }//GEN-LAST:event_btnXemThongTinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmB4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXemThongTin;
    private javax.swing.JComboBox<String> cboChon;
    private javax.swing.JLabel lblChon;
    private javax.swing.JLabel lblKichThuoc;
    private javax.swing.JLabel lblKieu;
    private javax.swing.JLabel lblMota;
    private javax.swing.JPanel pnNhap;
    private javax.swing.JPanel pnXuat;
    private javax.swing.JTextField txtKichThuoc;
    private javax.swing.JTextField txtKieu;
    private javax.swing.JTextField txtMoTa;
    // End of variables declaration//GEN-END:variables
}
