
package project;
// import java.sql.*;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.*;


public class QuanLy2 extends javax.swing.JFrame {
 
    String acc;
    private DefaultTableModel dtm=new DefaultTableModel();
    
    Connection conn;
    Statement nhap;
    String gt;
    String id;
    int ktselectrow= -1;
    int indexrow,idsearch;
    float d_toan,d_ly,d_hoa,d_sinh,d_tin,d_van,d_su,d_dia,d_en,d_gdcd,tbc;
    String xeploai;
    public QuanLy2(String Acc) {
        acc = Acc;
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jLabel2.setText("Xin chào "+acc+"! Bạn đang đăng nhập bằng quyền quản trị.");
        try
        {
            conn= DriverManager.getConnection("jdbc:sqlserver://THANHTRUNGIT\\SQLEXPRESS:49879;databaseName=qlsv","sa","123456");
            nhap =conn.createStatement();
        }
        catch (Exception e)
        {
            System.out.print("Lỗi");
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbhoten = new javax.swing.JLabel();
        hoten = new javax.swing.JTextField();
        lbns = new javax.swing.JLabel();
        ns = new javax.swing.JTextField();
        ten = new javax.swing.JTextField();
        lbmasv = new javax.swing.JLabel();
        masv = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbtoan = new javax.swing.JLabel();
        tf_toan = new javax.swing.JTextField();
        tf_ly = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_hoa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_sinh = new javax.swing.JTextField();
        lbsinh = new javax.swing.JLabel();
        tf_tin = new javax.swing.JTextField();
        lbtin = new javax.swing.JLabel();
        lbvan = new javax.swing.JLabel();
        tf_van = new javax.swing.JTextField();
        tf_su = new javax.swing.JTextField();
        lbsu = new javax.swing.JLabel();
        tf_dia = new javax.swing.JTextField();
        lbdia = new javax.swing.JLabel();
        lben = new javax.swing.JLabel();
        tf_en = new javax.swing.JTextField();
        tf_gdcd = new javax.swing.JTextField();
        lbgdcd = new javax.swing.JLabel();
        tf_tbc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lb_xeploai = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Them = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        del = new javax.swing.JButton();
        btup = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ev_idsearch = new javax.swing.JComboBox<>();
        tf_timkiem = new javax.swing.JTextField();
        bt_timkiem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT MANAGER FORM");
        setBackground(new java.awt.Color(255, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã SV", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin HS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 148, 255))); // NOI18N

        lbhoten.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbhoten.setText("Full Name     :");

        lbns.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbns.setText("Year of Birth:");

        ns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nsActionPerformed(evt);
            }
        });

        ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenActionPerformed(evt);
            }
        });

        lbmasv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbmasv.setText("ID Student   :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbmasv)
                    .addComponent(lbhoten)
                    .addComponent(lbns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ns)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ten, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                    .addComponent(masv))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbmasv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbhoten)
                    .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbns)
                    .addComponent(ns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Điểm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 148, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lbtoan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbtoan.setText("Toán");

        tf_toan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_toanKeyPressed(evt);
            }
        });

        tf_ly.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_lyKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Lý");

        tf_hoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_hoaKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Hóa");

        tf_sinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_sinhKeyPressed(evt);
            }
        });

        lbsinh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbsinh.setText("Sinh");

        tf_tin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_tinKeyPressed(evt);
            }
        });

        lbtin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbtin.setText("Tin Học");

        lbvan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbvan.setText("Văn");

        tf_van.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_vanKeyPressed(evt);
            }
        });

        tf_su.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_suKeyPressed(evt);
            }
        });

        lbsu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbsu.setText("Sử");

        tf_dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_diaKeyPressed(evt);
            }
        });

        lbdia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbdia.setText("Địa");

        lben.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lben.setText("English");

        tf_en.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_enKeyPressed(evt);
            }
        });

        lbgdcd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbgdcd.setText("GDCD");

        tf_tbc.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Học Lực :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Điểm Trung Bình :");

        lb_xeploai.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_sinh, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_hoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbdia, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbgdcd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lben)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_gdcd, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(tf_en)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tbc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_toan, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_ly, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbvan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_dia, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(tf_tin)
                                    .addComponent(tf_van)
                                    .addComponent(tf_su))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_xeploai)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtoan)
                    .addComponent(tf_toan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtin)
                    .addComponent(tf_tin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lben)
                    .addComponent(tf_en, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_ly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbvan)
                    .addComponent(tf_van, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbgdcd)
                    .addComponent(tf_gdcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_hoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_su, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbsu))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbsinh)
                    .addComponent(tf_sinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdia)
                    .addComponent(tf_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(lb_xeploai)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thao Tác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 148, 255))); // NOI18N

        Them.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/1465495989_plus-sign.png"))); // NOI18N
        Them.setText("ADD");
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        Refresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/1465496159_repeat.png"))); // NOI18N
        Refresh.setText(" Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        del.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/1465496103_remove-sign.png"))); // NOI18N
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        btup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/1465496272_ok-sign.png"))); // NOI18N
        btup.setText("Update");
        btup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupActionPerformed(evt);
            }
        });

        jButton1.setText("Xem Báo cáo sai Điểm từ học sinh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Them)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btup, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Them)
                    .addComponent(Refresh)
                    .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 148, 255))); // NOI18N

        ev_idsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn phương thức tìm kiếm", "Theo Tên", "Theo Mã" }));
        ev_idsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ev_idsearchActionPerformed(evt);
            }
        });

        bt_timkiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/1465502913_search.png"))); // NOI18N
        bt_timkiem.setText("Tìm Kiếm");
        bt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_timkiemActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/1465496159_repeat.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ev_idsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_timkiem))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(51, 51, 51))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ev_idsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Xin chào !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel2))
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        ResultSet resultSet;
        int d=0;
        try {   
            
            resultSet=   nhap.executeQuery("select * from qlsinhvien");
            while(resultSet.next())
            {
            if (resultSet.getString(1).equals(masv.getText()))
                d++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLy2.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (d>0)
        {
          JOptionPane.showMessageDialog(null, "Lỗi Mã Sinh Viên đã tồn tại!",
                  "Notification", JOptionPane.INFORMATION_MESSAGE);  
        }
        else 
        {
        try {
            d_toan = Float.parseFloat(tf_toan.getText());
            d_ly = Float.parseFloat(tf_ly.getText());
             d_hoa = Float.parseFloat(tf_hoa.getText());
            d_sinh = Float.parseFloat(tf_sinh.getText());
            d_tin = Float.parseFloat(tf_tin.getText());
            d_van = Float.parseFloat(tf_van.getText());
            d_su = Float.parseFloat(tf_su.getText());
            d_dia = Float.parseFloat(tf_dia.getText());
            d_en = Float.parseFloat(tf_en.getText());
            d_gdcd = Float.parseFloat(tf_gdcd.getText());
            if (d_toan<0 || d_ly<0|| d_hoa<0 || d_sinh<0 || d_tin<0 || d_van<0 || d_su<0 || d_dia<0 || d_en<0 || d_gdcd<0)
            {
                JOptionPane.showMessageDialog(null, "Lỗi nhập dữ liệu Điểm!",
                  "Notification", JOptionPane.INFORMATION_MESSAGE);
            }
            else 
            {
                
            
            tbc=(d_toan+d_ly+d_hoa+d_sinh+d_tin+d_van+d_su+d_dia+d_en+d_gdcd)/10;
            
            tf_tbc.setText(String.valueOf(tbc));
            if(tbc>=8)
                lb_xeploai.setText("Giỏi");
            else 
                if(tbc>=6.5)
                    lb_xeploai.setText("Khá");
                else 
                    if(tbc>=3.5)
                        lb_xeploai.setText("Trung Bình");
                    else 
                        lb_xeploai.setText("Yếu");
            if(tbc>=8)
                xeploai ="Giỏi";
            else 
                if(tbc>=6.5)
                    xeploai ="Khá";
                else 
                    if(tbc>=3.5)
                        xeploai ="Trung Bình";
                    else 
                        xeploai ="Yếu";
            // sql nhập dữ liệu
            nhap.executeUpdate("Insert into qlsinhvien (Ma,Ho,Ten,NS,Toan,Ly,Hoa,Sinh,Tin,Van,Su,Dia,English,GDCD,TBC,XepLoai) VALUES (\'"+masv.getText()+"\',N\'"+hoten.getText()+"\',N\'"+ten.getText()+"\',\'"+ns.getText()+"\',"+d_toan+","+d_ly+","+d_hoa+","+d_sinh+","+d_tin+","+d_van+","+d_su+","+d_dia+","+d_en+","+d_gdcd+","+tbc+",N\'"+xeploai+"\')");
            dtm.setRowCount(0);
        LoadDatalenTable();
        JOptionPane.showMessageDialog(null, " Add Complete!! ",
                  "Notification", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
           System.out.print(e);
        }
        }
        
    }//GEN-LAST:event_ThemActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        
        masv.setText("");
        hoten.setText("");
        ten.setText("");
        ns.setText("");
        tf_toan.setText(""); tf_ly.setText(""); tf_hoa.setText(""); tf_sinh.setText(""); tf_tin.setText("");
        tf_van.setText(""); tf_su.setText(""); tf_dia.setText(""); tf_en.setText(""); tf_gdcd.setText("");
        tf_tbc.setText(""); lb_xeploai.setText("Default");
        
    }//GEN-LAST:event_RefreshActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        /* int rowIndex = jTable1.getSelectedRow();
        id =(int) jTable1.getValueAt(rowIndex,0); */
         indexrow = jTable1.getSelectedRow();
         id= (String) jTable1.getValueAt(indexrow,0);
         ktselectrow=indexrow;
         
        
        ///// set gia tri len bang Updates
        masv.setText((String) jTable1.getValueAt(indexrow,0));
        hoten.setText((String) jTable1.getValueAt(indexrow,1));
        ten.setText((String) jTable1.getValueAt(indexrow,2));
        ns.setText((String) jTable1.getValueAt(indexrow,3));
        tf_toan.setText((String) jTable1.getValueAt(indexrow,4));
        tf_ly.setText((String) jTable1.getValueAt(indexrow,5));
        tf_hoa.setText((String) jTable1.getValueAt(indexrow,6));
        tf_sinh.setText((String) jTable1.getValueAt(indexrow,7));
        tf_tin.setText((String) jTable1.getValueAt(indexrow,8));
        tf_van.setText((String) jTable1.getValueAt(indexrow,9));
        tf_su.setText((String) jTable1.getValueAt(indexrow,10));
        tf_dia.setText((String) jTable1.getValueAt(indexrow,11));
        tf_en.setText((String) jTable1.getValueAt(indexrow,12));
        tf_gdcd.setText((String) jTable1.getValueAt(indexrow,13));
        tf_tbc.setText((String) jTable1.getValueAt(indexrow,14));
        lb_xeploai.setText((String) jTable1.getValueAt(indexrow,15));
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        
        if (ktselectrow==-1)
        {
            JOptionPane.showMessageDialog(null, " Chưa chọn đối tượng cần Xóa!! ",
                  "Notification", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            ktselectrow=-1;
            try {
                nhap.executeUpdate("DELETE FROM qlsinhvien WHERE Ma=\'"+id+"\'");



            }
            catch (Exception e)
            {
                System.out.print(e);
            }

            dtm.setRowCount(0);
            LoadDatalenTable();
            JOptionPane.showMessageDialog(null, " DELETE Complete!! ",
                      "Notification", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_delActionPerformed

    private void nsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nsActionPerformed
    }//GEN-LAST:event_nsActionPerformed

    private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenActionPerformed

    private void btupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupActionPerformed
        
        if (ktselectrow==-1)
        {
            JOptionPane.showMessageDialog(null, "Chưa chọn đối tượng cần Cập nhật !! ",
                  "Notification", JOptionPane.INFORMATION_MESSAGE);
        }
        else 
        {
            
            d_toan = Float.parseFloat(tf_toan.getText());
            d_ly = Float.parseFloat(tf_ly.getText());
            d_hoa = Float.parseFloat(tf_hoa.getText());
            d_sinh = Float.parseFloat(tf_sinh.getText());
            d_tin = Float.parseFloat(tf_tin.getText());
            d_van = Float.parseFloat(tf_van.getText());
            d_su = Float.parseFloat(tf_su.getText());
            d_dia = Float.parseFloat(tf_dia.getText());
            d_en = Float.parseFloat(tf_en.getText());
            d_gdcd = Float.parseFloat(tf_gdcd.getText());
            if (d_toan<0 || d_ly<0|| d_hoa<0 || d_sinh<0 || d_tin<0 || d_van<0 || d_su<0 || d_dia<0 || d_en<0 || d_gdcd<0)
            {
                JOptionPane.showMessageDialog(null, "Lỗi nhập dữ liệu Điểm!",
                  "Notification", JOptionPane.INFORMATION_MESSAGE);
            }
            else 
            {
                ktselectrow=-1;
            tbc=(d_toan+d_ly+d_hoa+d_sinh+d_tin+d_van+d_su+d_dia+d_en+d_gdcd)/10;
            
            tf_tbc.setText(String.valueOf(tbc));
            if(tbc>=8)
                lb_xeploai.setText("Giỏi");
            else 
                if(tbc>=6.5)
                    lb_xeploai.setText("Khá");
                else 
                    if(tbc>=3.5)
                        lb_xeploai.setText("Trung Bình");
                    else 
                        lb_xeploai.setText("Yếu");
            
        try {
            nhap.executeUpdate("UPDATE qlsinhvien\n" +
                    "SET Ma=\'"+masv.getText()+"\',Ho=N\'"+hoten.getText()+"\',Ten=N\'"+ten.getText()+"\',NS=N\'"+ns.getText()+"\',Toan="+d_toan+",Ly="+d_ly+",Hoa="+d_hoa+",Sinh="+d_sinh+",Tin="+d_tin+",Van="+d_van+",Su="+d_su+",Dia="+d_dia+",EngLish="+d_en+",GDCD="+d_gdcd+",Tbc="+tbc+",XepLoai=N\'"+lb_xeploai.getText()+"\'" +
                    "WHERE Ma=\'"+id+"\'");
        } catch (SQLException ex) {
            Logger.getLogger(QuanLy2.class.getName()).log(Level.SEVERE, null, ex);
        }
        dtm.setRowCount(0);
        LoadDatalenTable();
        JOptionPane.showMessageDialog(null, " UPDATES Student ID "+id+" Full Name: "+hoten.getText()+" "+ten.getText()+" Complete!! ",
                  "Notification", JOptionPane.WARNING_MESSAGE);
        }
        //end
        }
            
        
    }//GEN-LAST:event_btupActionPerformed

    private void ev_idsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ev_idsearchActionPerformed
         idsearch = ev_idsearch.getSelectedIndex();
        
    }//GEN-LAST:event_ev_idsearchActionPerformed

    private void bt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_timkiemActionPerformed
        if (idsearch==2)
        { dtm.setRowCount(0); 
           TimKiemTheoMa();
        }
        else 
        if (idsearch==1)
        { 
            dtm.setRowCount(0); 
            TimKiemTheoTen();
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "Chưa chọn phương thức Tìm Kiếm",
                  "Notification", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_bt_timkiemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dtm.setRowCount(0);
        LoadDatalenTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tf_toanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_toanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tf_ly.requestFocus();
        }
    }//GEN-LAST:event_tf_toanKeyPressed

    private void tf_lyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_lyKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tf_hoa.requestFocus();
        }
    }//GEN-LAST:event_tf_lyKeyPressed

    private void tf_hoaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_hoaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tf_sinh.requestFocus();
        }
    }//GEN-LAST:event_tf_hoaKeyPressed

    private void tf_sinhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_sinhKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tf_tin.requestFocus();
        }
    }//GEN-LAST:event_tf_sinhKeyPressed

    private void tf_tinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_tinKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tf_van.requestFocus();
        }
    }//GEN-LAST:event_tf_tinKeyPressed

    private void tf_vanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_vanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tf_su.requestFocus();
        }
    }//GEN-LAST:event_tf_vanKeyPressed

    private void tf_suKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_suKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tf_dia.requestFocus();
        }
    }//GEN-LAST:event_tf_suKeyPressed

    private void tf_diaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_diaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tf_en.requestFocus();
        }
    }//GEN-LAST:event_tf_diaKeyPressed

    private void tf_enKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_enKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tf_gdcd.requestFocus();
        }
    }//GEN-LAST:event_tf_enKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DSBaoCao dsbc = new DSBaoCao();
        dsbc.setVisible(true);
        dsbc.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void TimKiemTheoTen()
    {
        int d=0;
        try {
            Vector row,colum;
            int numcol; // số cột
            colum=new Vector();
            
            ResultSet resultSet=    nhap.executeQuery("select * from qlsinhvien WHERE Ten=N\'"+tf_timkiem.getText()+"\' ORDER BY Ten");
            ResultSetMetaData metaData =resultSet.getMetaData();
            numcol=metaData.getColumnCount();
            
           
            
            for (int i=1; i<=numcol;i++)
            {
                colum.add(metaData.getColumnName(i));
            }
            dtm.setColumnIdentifiers(colum);
            while (resultSet.next())
            {
                d++;
                row = new Vector();
                for (int i=1; i<=numcol;i++)
                    row.add(resultSet.getString(i));
                dtm.addRow(row);
                
            }
             jTable1.setModel(dtm);
             if (d==0)
             {
                 dtm.setRowCount(0);
                 LoadDatalenTable();
                 JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả !!",
                  "Notification", JOptionPane.WARNING_MESSAGE);
             }
                 
                 
        } 
        catch (SQLException ex) {
            Logger.getLogger(QuanLy2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void TimKiemTheoMa()
    {
        int d=0;
        try {
            Vector row,colum;
            int numcol; // số cột
            colum=new Vector();
            
            ResultSet resultSet=    nhap.executeQuery("select * from qlsinhvien WHERE MA=\'"+tf_timkiem.getText()+"\' ORDER BY Ten");
            ResultSetMetaData metaData =resultSet.getMetaData();
            numcol=metaData.getColumnCount();
            
           
            
            for (int i=1; i<=numcol;i++)
            {
                colum.add(metaData.getColumnName(i));
            }
            dtm.setColumnIdentifiers(colum);
            while (resultSet.next())
            {
                d++;
                row = new Vector();
                for (int i=1; i<=numcol;i++)
                    row.add(resultSet.getString(i));
                dtm.addRow(row);
                
            }
             jTable1.setModel(dtm);
             if (d==0)
             {
                 dtm.setRowCount(0);
                 LoadDatalenTable();
                 JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả !!",
                  "Notification", JOptionPane.WARNING_MESSAGE);
             }
        } 
        catch (SQLException ex) {
            Logger.getLogger(QuanLy2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public void LoadDatalenTable()
    {
        try {
            Vector row,colum;
            int numcol; // số cột
            colum=new Vector();
            
            ResultSet resultSet=    nhap.executeQuery("select * from qlsinhvien ORDER BY Ten");
            ResultSetMetaData metaData =resultSet.getMetaData();
            numcol=metaData.getColumnCount();
            
           
            String[] cot = {"Mã SV","Họ","Tên","Năm Sinh","Toán","Lý","Hóa","Sinh","Tin","Văn","Sử","Địa","English","GDCD","Điểm TB","Xếp Loại"};
            for (int i = 0; i < cot.length; i++) {
                colum.add(cot[i]);
            }
//            for (int i=1; i<=numcol;i++)
//            {
//                colum.add(metaData.getColumnName(i));
//            }
            dtm.setColumnIdentifiers(colum);
            while (resultSet.next())
            {
                row = new Vector();
                for (int i=1; i<=numcol;i++)
                    row.add(resultSet.getString(i));
                dtm.addRow(row);
                
            }
             jTable1.setModel(dtm);
        } 
        catch (SQLException ex) {
            Logger.getLogger(QuanLy2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
     public void DelTable()
    {
        try {
            Vector row,colum;
            int numcol; // số cột
            colum=new Vector();
            
            ResultSet resultSet=    nhap.executeQuery("select * from dtsinhvien");
            ResultSetMetaData metaData =resultSet.getMetaData();
            numcol=metaData.getColumnCount();
            int hang=nhap.getMaxRows();
            
            for (int i=1; i<=numcol;i++)
            {
                colum.add(metaData.getColumnName(i));
            }
            dtm.setColumnIdentifiers(colum);
            
            
                  
               
            
             jTable1.setModel(dtm);
        } 
        catch (SQLException ex) {
            Logger.getLogger(QuanLy2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLy2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLy2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLy2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLy2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
      /*
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLy2 from = new QuanLy2();
                from.setVisible(true);
                from.setLocationRelativeTo(null);
                from.LoadDatalenTable();
            }
        }); */
    }


   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Them;
    private javax.swing.JButton bt_timkiem;
    private javax.swing.JButton btup;
    private javax.swing.JButton del;
    private javax.swing.JComboBox<String> ev_idsearch;
    private javax.swing.JTextField hoten;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_xeploai;
    private javax.swing.JLabel lbdia;
    private javax.swing.JLabel lben;
    private javax.swing.JLabel lbgdcd;
    private javax.swing.JLabel lbhoten;
    private javax.swing.JLabel lbmasv;
    private javax.swing.JLabel lbns;
    private javax.swing.JLabel lbsinh;
    private javax.swing.JLabel lbsu;
    private javax.swing.JLabel lbtin;
    private javax.swing.JLabel lbtoan;
    private javax.swing.JLabel lbvan;
    private javax.swing.JTextField masv;
    private javax.swing.JTextField ns;
    private javax.swing.JTextField ten;
    private javax.swing.JTextField tf_dia;
    private javax.swing.JTextField tf_en;
    private javax.swing.JTextField tf_gdcd;
    private javax.swing.JTextField tf_hoa;
    private javax.swing.JTextField tf_ly;
    private javax.swing.JTextField tf_sinh;
    private javax.swing.JTextField tf_su;
    private javax.swing.JTextField tf_tbc;
    private javax.swing.JTextField tf_timkiem;
    private javax.swing.JTextField tf_tin;
    private javax.swing.JTextField tf_toan;
    private javax.swing.JTextField tf_van;
    // End of variables declaration//GEN-END:variables
}
