package Project.View;

import Project.Controller.SubjectsDAO;
import Project.Model.Subjects;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

public class FrmListSubjects extends javax.swing.JFrame {

  /**
   * Creates new form frmListSubjects
   */
  public FrmListSubjects() {
    initComponents();
    setLocationRelativeTo(null);
    setResizable(false);
    getRootPane().setDefaultButton(btnSearch);
    btnSearch.requestFocus();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtID = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txtname = new javax.swing.JTextField();
    btnSearch = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tbSubject = new javax.swing.JTable();
    btnCan = new javax.swing.JButton();
    btnDel = new javax.swing.JButton();
    btnEdit = new javax.swing.JButton();
    btnAdd = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);
    addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        formMouseClicked(evt);
      }
    });
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

    jLabel1.setText("ID Subject: ");

    txtID.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtIDKeyReleased(evt);
      }
    });

    jLabel2.setText("Name Subject: ");

    txtname.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtnameKeyReleased(evt);
      }
    });

    btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Images/ZoomHS.png"))); // NOI18N
    btnSearch.setText("Search");
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSearchActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(26, 26, 26)
        .addComponent(btnSearch)
        .addContainerGap(104, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2)
          .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSearch))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("List Subject"));

    tbSubject.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null}
      },
      new String [] {
        "ID Subject", "Name Subject", "Credit"
      }
    ));
    jScrollPane1.setViewportView(tbSubject);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    btnCan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Images/cancel.gif"))); // NOI18N
    btnCan.setText("Cancel");
    btnCan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCanActionPerformed(evt);
      }
    });

    btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Images/delete.png"))); // NOI18N
    btnDel.setText("Delete");
    btnDel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDelActionPerformed(evt);
      }
    });

    btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Images/book_edit.png"))); // NOI18N
    btnEdit.setText("Edit");
    btnEdit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditActionPerformed(evt);
      }
    });

    btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Images/add-icon.png"))); // NOI18N
    btnAdd.setText("Add");
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnAdd)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnEdit)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnDel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnCan)
        .addContainerGap())
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnCan)
          .addComponent(btnDel)
          .addComponent(btnEdit)
          .addComponent(btnAdd))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    this.setTitle("Information of subject");
    display();
  }//GEN-LAST:event_formWindowOpened

  private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    FrmUpdateSubject frm = new FrmUpdateSubject();
    frm.setVisible(true);
  }//GEN-LAST:event_btnAddActionPerformed

  private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    int select = tbSubject.getSelectedRow();
    if (select == -1) {
      JOptionPane.showMessageDialog(this,
              "Please choose subject");
      return;
    }
    String id = (String) tbSubject.getValueAt(select, 0);
    FrmUpdateSubject frm = new FrmUpdateSubject();
    frm.setIdS(id);
    frm.setVisible(true);
  }//GEN-LAST:event_btnEditActionPerformed

  private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
    int select = tbSubject.getSelectedRow();
    if (select == -1) {
      JOptionPane.showMessageDialog(this,
              "Please choose Subject");
      return;
    }
    SubjectsDAO svd = new SubjectsDAO();
    String id = (String) tbSubject.getValueAt(select, 0);
    if (JOptionPane.showConfirmDialog(this, "Do you want to delete", "Are you sure to delete "
            + "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
      boolean kq = svd.delete(id);
      if (kq) {
        JOptionPane.showMessageDialog(rootPane, "Sucess");
        display();
      }
    }
  }//GEN-LAST:event_btnDelActionPerformed

  private void btnCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanActionPerformed
    this.dispose();
  }//GEN-LAST:event_btnCanActionPerformed

  private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    search();
  }//GEN-LAST:event_btnSearchActionPerformed

  private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    display();
  }//GEN-LAST:event_formMouseClicked

  private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
      txtname.requestFocus();
    }
  }//GEN-LAST:event_txtIDKeyReleased

  private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
   
      search();
    
  }//GEN-LAST:event_txtnameKeyReleased

  private void search() {
    String name = txtname.getText();
    String id = txtID.getText();
    List<Subjects> lst = new ArrayList<>();
    if (name != null && (id.isEmpty() || id == null)) {
      lst = SubjectsDAO.getInstance().find("", name);
    } else if (id != null && (name.isEmpty() || name == null)) {
      lst = SubjectsDAO.getInstance().find(id, "");
    } else {
      lst = SubjectsDAO.getInstance().find(id, name);
    }
    displayList(lst);
  }

  public void display() {
    displayList(SubjectsDAO.getInstance().getAll());
  }

  public void displayList(List<Subjects> lstSub) {
    String colTieuDe[] = new String[]{"ID", "Name", "Credit"};
    DefaultTableModel model = new DefaultTableModel(colTieuDe, 0);
    Object objSub[];
    for (Subjects sb : lstSub) {
      objSub = new Object[colTieuDe.length];
      objSub[0] = sb.getIdSubject();
      objSub[1] = sb.getNameSubject();
      objSub[2] = sb.getCredit();
      model.addRow(objSub);
    }
    tbSubject.setModel(model);
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrmListSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrmListSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrmListSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrmListSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        try {
          UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
        }
        new FrmListSubjects().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdd;
  private javax.swing.JButton btnCan;
  private javax.swing.JButton btnDel;
  private javax.swing.JButton btnEdit;
  private javax.swing.JButton btnSearch;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tbSubject;
  private javax.swing.JTextField txtID;
  private javax.swing.JTextField txtname;
  // End of variables declaration//GEN-END:variables
}
